#language: generic

services:
  - docker

before_install:
  - docker build -t $DOCKER_USERNAME/tests -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true $DOCKER_USERNAME/tests npm run test

after_success:
  #Login to docker cli
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
  #Build the images
  - docker build -t $DOCKER_USERNAME/multi-client ./client
  - docker build -t $DOCKER_USERNAME/multi-nginx ./nginx
  - docker build -t $DOCKER_USERNAME/multi-server ./server
  - docker build -t $DOCKER_USERNAME/multi-worker ./worker
  #take those images and push them to github
  - docker push $DOCKER_USERNAME/multi-client
  - docker push $DOCKER_USERNAME/multi-nginx
  - docker push $DOCKER_USERNAME/multi-server
  - docker push $DOCKER_USERNAME/multi-worker